name: Test Workflow1

on:
  workflow_dispatch:
    inputs:
      ilk_hesap_email:
        description: 'First Account Email'
        required: true
      ilk_hesap_sifre:
        description: 'First Account Password'
        required: true
      username:
        description: 'Username'
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log input parameters
        run: |
          echo "First Account Email: ${{ github.event.inputs.ilk_hesap_email }}"
          echo "First Account Password: ${{ github.event.inputs.ilk_hesap_sifre }}"             
          echo "Username: ${{ github.event.inputs.username }}"
