name: Test Workflow2

on:
  workflow_dispatch:
    inputs:
      ilk_hesap_email:
        description: 'First Account Email'
        required: true
      ilk_hesap_sifre:
        description: 'First Account Password'
        required: true
      taraftar_kart_tc:
        description: 'Id number'
        required: false
      matchName:
        description: 'match name'
        required: false
      username:
        description: 'Username'
        required: true
      

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Log input parameters
        run: |
          echo "First Account Email: ${{ github.event.inputs.ilk_hesap_email }}"
          echo "First Account Password: ${{ github.event.inputs.ilk_hesap_sifre }}"   
          echo "Id Number: ${{ github.event.inputs.taraftar_kart_tc }}"  
          echo "Match  Name: ${{ github.event.inputs.matchName }}"   
          echo "Username: ${{ github.event.inputs.username }}"
